name: Build V8 (Single)

on: 
  workflow_dispatch:
    inputs:
      host:
        type: choice
        description: Host
        options:
          - ubuntu-20.04
          - macos-10.15
          - windows-2019
      target:
        type: choice
        description: Target
        options:
          - x86_64-linux-gnu
          - x86_64-macos-gnu
          - x86_64-windows-msvc
          - x86_64-windows-gnu
          - aarch64-macos-gnu
      mode:
        type: choice
        description: Mode
        options:
          - release
      toolchain:
        type: choice
        description: Toolchain
        options:
          - v8
          - zig

jobs:
  build:
    name: host=${{ github.event.inputs.host }} target=${{ github.event.inputs.target }} mode=${{ github.event.inputs.mode }} tc=${{ github.event.inputs.toolchain }}
    runs-on: ${{ github.event.inputs.host }}
    env:
      ARCH_OS: >-
        ${{ fromJson('{
          "x86_64-windows-gnu": "x86_64-windows",
          "x86_64-windows-msvc": "x86_64-windows",
          "x86_64-linux-gnu": "x86_64-linux",
          "x86_64-macos-gnu": "x86_64-macos",
          "aarch64-macos-gnu": "aarch64-macos",
        }')[github.event.inputs.target] }}
      ZIG_TARGET_FLAG: >-
        ${{ fromJson('{
          "x86_64-windows-gnu": "-Dtarget=x86_64-windows-gnu -Dcpu=baseline",
          "x86_64-windows-msvc": "-Dtarget=x86_64-windows-msvc -Dcpu=baseline",
          "x86_64-linux-gnu": "-Dtarget=x86_64-linux-gnu -Dcpu=baseline",
          "x86_64-macos-gnu": "-Dtarget=x86_64-macos.10.13-gnu -Dcpu=baseline",
          "aarch64-macos-gnu": "-Dtarget=aarch64-macos.11-gnu -Dcpu=baseline",
        }')[github.event.inputs.target] }}
      LIB_NAME: ${{ contains(github.event.inputs.target, 'windows') && 'c_v8' || 'libc_v8' }}
      LIB_EXT: ${{ contains(github.event.inputs.target, 'windows') && 'lib' || 'a' }}
      BUILD_TARGET: ${{ github.event.inputs.target }}
      BUILD_MODE: ${{ github.event.inputs.mode }}
      BUILD_TOOLCHAIN: ${{ github.event.inputs.toolchain }}
    steps:
      - name: Clone repo.
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Get build tag.
        shell: bash
        # Need single quotes or path sep becomes escapes on windows host. xargs does trimming.
        run: echo "BUILD_TAG=$(cat '${{ github.workspace }}/V8_REVISION' | xargs)" >> $GITHUB_ENV

      - name: Create/Update tag.
        uses: actions/github-script@v5
        with:
          script: |
            const ref = 'tags/${{ env.BUILD_TAG }}';
            const res = await github.rest.git.listMatchingRefs({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/${{ env.BUILD_TAG }}',
            });
            if (res.data.length > 0) {
              await github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'tags/${{ env.BUILD_TAG }}',
                sha: context.sha,
              });
            } else {
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                // Only create needs full path
                ref: 'refs/tags/${{ env.BUILD_TAG }}',
                sha: context.sha,
              });
            }

      - name: Install zig.
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.11.0

      - name: Cache.
        if: env.BUILD_TOOLCHAIN == 'zig'
        uses: actions/cache@v2
        with:
          path: |-
            ~/.cache/zig
          key:
            c_v8-${{ env.BUILD_TARGET }}-${{ env.BUILD_MODE }}-zig2
          restore-keys:
            c_v8-${{ env.BUILD_TARGET }}-${{ env.BUILD_MODE }}-zig2

      - name: Cache.
        if: env.BUILD_TOOLCHAIN == 'v8'
        uses: actions/cache@v2
        with:
          # Restore sccache so subsequent runs can reuse the cache.
          # TODO: Might be useful to restore some of v8 source deps so get-v8 does less work.
          path: |-
            sccache
          key:
            # The cache can behave unexpectedly (usually happens when we change the path), so we just increase a simple id counter to create a new cache.
            c_v8-${{ env.BUILD_TARGET }}-${{ env.BUILD_MODE }}-2
          restore-keys:
            # Reuse a previous cache.
            c_v8-${{ env.BUILD_TARGET }}-${{ env.BUILD_MODE }}-

      - name: Install and start sccache.
        if: env.BUILD_TOOLCHAIN == 'v8'
        shell: pwsh
        env:
          SCCACHE_DIR: ${{ github.workspace }}/sccache
          # Compiling all of v8 takes up about 100M for debug builds so this is a good starting point.
          SCCACHE_CACHE_SIZE: 128M
          SCCACHE_IDLE_TIMEOUT: 0
        run: |
          $version = "v0.2.15"
          $platform =
            @{ "macOS"   = "x86_64-apple-darwin"
               "Linux"   = "x86_64-unknown-linux-musl"
               "Windows" = "x86_64-pc-windows-msvc"
             }.${{ runner.os }}
          $basename = "sccache-$version-$platform"
          $url = "https://github.com/mozilla/sccache/releases/download/" +
                 "$version/$basename.tar.gz"
          cd ~
          curl -LO $url
          tar -xzvf "$basename.tar.gz"
          chmod a+x $basename/sccache
          . $basename/sccache --start-server
          echo "$(pwd)/$basename" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Get V8 Tools.
        run: zig build get-tools

      - name: Get V8 Source.
        run: zig build get-v8

      - name: Build release.
        if: env.BUILD_MODE == 'release' && env.BUILD_TOOLCHAIN == 'v8'
        run: zig build -Drelease-safe ${{ env.ZIG_TARGET_FLAG }}

      - name: Build release.
        if: env.BUILD_MODE == 'release' && env.BUILD_TOOLCHAIN == 'zig'
        run: zig build -Drelease-safe ${{ env.ZIG_TARGET_FLAG }} -Dzig-toolchain

      - name: Build debug.
        if: env.BUILD_MODE == 'debug'
        run: zig build

      - name: Copy binary.
        if: env.BUILD_TARGET != 'x86_64-windows-gnu'
        continue-on-error: true
        run: cp
          v8-build/${{ env.ARCH_OS }}/${{ env.BUILD_MODE }}/ninja/obj/zig/${{ env.LIB_NAME }}.${{ env.LIB_EXT }}
          v8-build/${{ env.LIB_NAME }}_${{ env.BUILD_TARGET }}_${{ env.BUILD_MODE }}_${{ env.BUILD_TAG }}.${{ env.LIB_EXT }}

      - name: Copy binary.
        if: env.BUILD_TARGET == 'x86_64-windows-gnu'
        continue-on-error: true
        run: cp
          v8-build/${{ env.ARCH_OS }}/${{ env.BUILD_MODE }}/ninja/obj/zig/libc_v8.a
          v8-build/${{ env.LIB_NAME }}_${{ env.BUILD_TARGET }}_${{ env.BUILD_MODE }}_${{ env.BUILD_TAG }}.${{ env.LIB_EXT }}

      - name: Github Release.
        uses: softprops/action-gh-release@v0.1.14
        # Github requires tags for releases.
        #if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: Release
          name: ${{ env.BUILD_TAG }}
          tag_name: ${{ env.BUILD_TAG }}
          files: v8-build/${{ env.LIB_NAME }}_${{ env.BUILD_TARGET }}_${{ env.BUILD_MODE }}_${{ env.BUILD_TAG }}.${{ env.LIB_EXT }}

      - name: Stop sccache.
        if: env.BUILD_TOOLCHAIN == 'v8' && always()
        run: |
          sccache --show-stats
          sccache --stop-server
